### ISSUE TITLE
Feature: User can view art of a certain style from a time period

### ISSUE THREAD

**Issue by PaxtonRosenberg** [PaxtonRosenberg/Blank-Canvas#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="entry-form"]` to the HTML
- [x] Add a form with drop down menu options to select time period and style to the `div[data-view="entry-form"]`
- [x] Ensure the form is mobile responsive.
- [x] Make all inputs of the journal entry form `required`.
- [x] Listen for 'input' events on the 'time period' and 'style' inputs to update the query for the API.
- [x] Listen for 'submit' event on the form and:
- [x] Add the forms input values to the API endpoint
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
